# -*- coding: utf-8 -*-
"""Detección_de_Anomalias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16aZUfr7u-RxuyZWH6v5YhU8xvmWq1fXl

# **DETECCIÓN DE ANOMALÍAS**

# **Presentado por: Jim Flores Teves**
"""

#importamos librerias necesarias
import pandas as pd
import numpy as np

"""1. Creamos una DB de muestra"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (16.0, 6.0)

data = pd.DataFrame(np.random.randn(250))
data.plot()

#Histograma
data.hist()

data.std()

"""2. Definimos el techo y suelo para delimitar e identificar las anomalías"""

wind = 20 #define la ventana
sigma = 2  #sensibilidad estandar

data["suelo"] = data[0].rolling(window=wind)\
    .mean() - (sigma * data[0].rolling(window=wind).std())
data["techo"] = data[0].rolling(window=wind)\
    .mean() + (sigma * data[0].rolling(window=wind).std())
data.plot()

"""3. Definimos las anomalías"""

data["anom"] = data.apply(
    lambda row: row[0] if (row[0]<=row["suelo"] or row[0]>=row["techo"]) else 0, axis=1)

data.plot()

"""4. Ejemplo propio con una base de datos de Udemy"""

data_ = pd.read_csv("GraphicDesign.csv")
data_.head()

newdata = data_["numSubscribers"]
newdata

newdata.plot()

data_.drop(columns=['numReviews',	'numPublishedLectures'],inplace = True)
data_

data_.to_csv('data1.csv')



df = pd.read_csv('data1.csv', index_col=0)
df.plot()

wind = 15
sigma = 2

df["suelo"] = df["numSubscribers"].rolling(window=wind)\
    .mean() - (sigma * df["numSubscribers"].rolling(window=wind).std())
df["techo"] = df["numSubscribers"].rolling(window=wind)\
    .mean() + (sigma * df["numSubscribers"].rolling(window=wind).std())
df.plot()

df["anom"] = df.apply(
    lambda row: row["numSubscribers"] if (row["numSubscribers"]<=row["suelo"] or row["numSubscribers"]>=row["techo"]) else 0
, axis=1)
df.plot()

"""Referencias: David Martin
https://www.youtube.com/watch?v=6TyepQq9NBc&t=972s&ab_channel=DavidMart%C3%ADn
"""

