# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KRnq_fQeK521oUrlCfVOA2wlw_KBgLjp
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# %matplotlib inline

pizza=pd.read_csv('Pizza.csv')

pizza.info()

pizza.head()

var=pizza.drop(['brand'], axis=1)

var.describe()

norm_pizza=(var-var.min())/(var.max()-var.min())
norm_pizza

wcss=[]

for i in range (1,11):
  kmeans = KMeans(n_clusters=i,max_iter=600)
  kmeans.fit(norm_pizza)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,11),wcss)
plt.title('metodo del codo')
plt.xlabel('numero de cluster')
plt.ylabel('wcss')
plt.show

clustering= KMeans(n_clusters=4,max_iter=600)
clustering.fit(norm_pizza)

pizza['kmeans_cluster']= clustering.labels_
pizza.head()

from sklearn.decomposition import PCA

pca=PCA(n_components=2)
pca_pizza=pca.fit_transform(norm_pizza)
pca_pizza_df= pd.DataFrame(data= pca_pizza, columns=['comp1','comp2'])
pca_pizza_n= pd.concat ([pca_pizza_df, pizza[['kmeans_cluster']  ] ], axis=1)  
pca_pizza_n

fig=plt.figure(figsize=(6,6))

ax=fig.add_subplot(1,1,1)
ax.set_xlabel('comp1',fontsize=15)
ax.set_ylabel('comp2',fontsize=15)
ax.set_title('componentes pincipales', fontsize=20)

color_theme = np.array (["blue","green","orange","red"])
ax.scatter(x=pca_pizza_n.comp1,y=pca_pizza_n.comp2, 
           c=color_theme[pca_pizza_n.kmeans_cluster], s=50)
plt.show()

